#!/usr/bin/env python3
"""
ver_exp_ue_50ue_fixed.py — runs on pc801 (uehost1)

POWDER node mapping:
  core     = pc808   10.10.1.1   Open5GS EPC (MME+SGW+UPF)
  gnb1     = pc802   10.10.1.2   srsenb — one process per UE
  uehost1  = pc801   10.10.1.4   srsue  — one process per UE  ← this node

Fixes applied vs ver_exp_ue_50ue.py:
  1. Default route injected into each netns after attach (root cause of
     "attach OK but ping 100% loss").
  2. Per-UE dedicated iperf3 server port (5201+N) — eliminates "server busy"
     errors when running iperf3 sequentially; server loops are started on
     CORE_HOST before the ramp begins and are persistent (while-true).
  3. Ping waits up to 10 s for the route + ARP to settle after inject.
  4. iperf direction flag corrected: DL = server→UE uses -R (reverse),
     UL = UE→server has no flag.  Both use --json for reliable parsing.
  5. attach_error captured more precisely.
  6. UE process group kill uses SIGTERM first so NAS Detach is sent,
     preventing stale UPF PFCP sessions on next run.

Usage (on pc801):
    python3 ver_exp_ue_50ue_fixed.py v22_10 /opt/srsran_22_10/bin/srsue
"""

import sys, os, subprocess, time, json, re

# ── Node mapping ──────────────────────────────────────────────────────────────
CORE_IP   = "10.45.0.1"   # Open5GS UE subnet gateway (SGi side)
GNB1_IP   = "10.10.1.2"   # pc802 — ZMQ connect target for UE
IPERF_BASE_PORT = 5200     # per-UE port = 5200 + N

# ── Constants ─────────────────────────────────────────────────────────────────
VER             = sys.argv[1] if len(sys.argv) > 1 else "v22_10"
UE_BIN          = sys.argv[2] if len(sys.argv) > 2 else "/opt/srsran_22_10/bin/srsue"
N_UE            = 50
ATTACH_TIMEOUT  = 90   # seconds per UE
PING_COUNT      = 20
PING_SETTLE_S   = 5    # seconds to wait after injecting default route before pinging
OUT_DIR         = f"/tmp/ver_eval_50ue/{VER}"
SENTINEL        = f"{OUT_DIR}/UE_DONE"

os.makedirs(OUT_DIR, exist_ok=True)

def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}][{VER}] {msg}", flush=True)

def run(cmd, **kw):
    return subprocess.run(cmd, shell=True, **kw)

def kill_ue_graceful(n):
    """SIGTERM first (NAS Detach), then SIGKILL."""
    run(f"sudo pkill    -f 'srsue.*ue50_{n}\\.conf' 2>/dev/null || true")
    time.sleep(1.5)
    run(f"sudo pkill -9 -f 'srsue.*ue50_{n}\\.conf' 2>/dev/null || true")

def inject_default_route(n):
    """
    Add 'default dev tun_srsueN' inside netns ueN.
    This is the primary fix for ping/iperf failure after successful attach.
    srsue creates the tun interface and assigns an RFC1918 IP, but in some
    kernel/srsue version combinations the default route is NOT installed.
    """
    netns = f"ue{n}"
    tun   = f"tun_srsue{n}"
    # check first — avoid adding a duplicate
    chk = run(f"sudo ip netns exec {netns} ip route show default 2>/dev/null",
              capture_output=True, text=True)
    if "default" in chk.stdout:
        return True  # already present
    ret = run(f"sudo ip netns exec {netns} ip route add default dev {tun} 2>/dev/null || true")
    # verify
    chk2 = run(f"sudo ip netns exec {netns} ip route show default 2>/dev/null",
               capture_output=True, text=True)
    return "default" in chk2.stdout

def get_tun_ip(n):
    """Return the IP assigned to tun_srsueN inside netns ueN, or ''."""
    r = run(f"sudo ip netns exec ue{n} ip -4 -br addr show tun_srsue{n} 2>/dev/null",
            capture_output=True, text=True)
    m = re.search(r"(\d+\.\d+\.\d+\.\d+)/", r.stdout)
    return m.group(1) if m else ""

# ── CSV header ────────────────────────────────────────────────────────────────
HDR = (
    "ver,ue_id,n_active,attach_ms,attach_ok,attach_error,ue_ip,"
    "ping_avg_ms,ping_min_ms,ping_max_ms,ping_jitter_ms,ping_loss_pct,"
    "dl_1m_mbps,dl_1m_loss_pct,dl_5m_mbps,dl_5m_loss_pct,"
    "dl_10m_mbps,dl_10m_loss_pct,"
    "ul_1m_mbps,ul_1m_loss_pct,"
    "drop_detected,drop_reason"
)
CSV_PATH = f"{OUT_DIR}/ue_results_50ue.csv"
with open(CSV_PATH, "w") as f:
    f.write(HDR + "\n")

n_active = 0

for N in range(1, N_UE + 1):
    netns      = f"ue{N}"
    ue_conf    = f"/tmp/ue50_{N}.conf"   # generated by gen_configs_v22_50ue.py
    stdout_log = f"{OUT_DIR}/ue{N}_stdout.log"
    log_f      = f"{OUT_DIR}/ue{N}.log"

    log(f"--- UE{N} (active={n_active}) ---")

    # Pre-create network namespace (idempotent)
    run(f"sudo ip netns add {netns} 2>/dev/null || true")
    run(f"sudo ip netns exec {netns} ip link set lo up 2>/dev/null || true")

    # Config must exist
    if not os.path.exists(ue_conf):
        log(f"  UE{N}: SKIP — conf {ue_conf} missing")
        with open(CSV_PATH, "a") as f:
            f.write(f"{VER},{N},{n_active},0,FAIL,conf_missing,,"
                    ",,,,,,,,,,,,,,\n")
        continue

    kill_ue_graceful(N)
    time.sleep(0.5)

    # ── Start srsue ──────────────────────────────────────────────────────────
    t0 = time.time()
    with open(stdout_log, "w") as sl:
        p = subprocess.Popen(
            f"sudo {UE_BIN} {ue_conf} --log.filename={log_f}",
            shell=True, stdout=sl, stderr=sl)

    # ── Poll for attach ───────────────────────────────────────────────────────
    attached   = False
    attach_err = ""
    ue_ip      = ""
    for i in range(ATTACH_TIMEOUT):
        time.sleep(1)
        try:
            txt = open(stdout_log).read()
        except Exception:
            txt = ""

        if "Network attach successful" in txt:
            attached = True
            # prefer IP from sysfs tun interface (more reliable)
            ue_ip = get_tun_ip(N)
            if not ue_ip:
                m = re.search(r"10\.\d+\.\d+\.\d+", txt[txt.find("Network attach"):])
                if m:
                    ue_ip = m.group(0)
            break

        if p.poll() is not None:
            attach_err = "srsue_process_died"
            try:
                lines = open(stdout_log).readlines()
                attach_err = "|".join(l.strip() for l in lines[-3:])[:120].replace(",", ";")
            except Exception:
                pass
            break

        if re.search(
            r"Unrecognised option|Error initializing|assertion failed|bind.*in use",
            txt, re.I):
            try:
                lines = open(stdout_log).readlines()
                attach_err = "|".join(l.strip() for l in lines[-3:])[:120].replace(",", ";")
            except Exception:
                attach_err = "init_error"
            break

    attach_ms = int((time.time() - t0) * 1000)

    if not attached:
        if not attach_err:
            attach_err = f"timeout_{ATTACH_TIMEOUT}s"
        log(f"  UE{N}: FAIL ({attach_ms}ms) — {attach_err}")
        kill_ue_graceful(N)
        with open(CSV_PATH, "a") as f:
            f.write(f"{VER},{N},{n_active},{attach_ms},FAIL,{attach_err},,"
                    ",,,,,,,,,,,,,,\n")
        continue

    # ── FIX #1: inject default route into netns ───────────────────────────────
    route_ok = inject_default_route(N)
    if route_ok:
        log(f"  UE{N}: ATTACH OK {attach_ms}ms IP={ue_ip} (default route injected)")
    else:
        log(f"  UE{N}: ATTACH OK {attach_ms}ms IP={ue_ip} WARNING: could not inject default route")

    n_active += 1
    open(f"{OUT_DIR}/ue_progress", "w").write(str(n_active))

    # Wait for ARP/routing to settle
    time.sleep(PING_SETTLE_S)

    # ── Ping ─────────────────────────────────────────────────────────────────
    pr = run(
        f"sudo ip netns exec {netns} ping -c {PING_COUNT} -i 0.2 -W 2 {CORE_IP}",
        capture_output=True, text=True)
    ping_out = pr.stdout + pr.stderr
    with open(f"{OUT_DIR}/ue{N}_ping.txt", "w") as pf:
        pf.write(ping_out)

    p_rtt = re.search(
        r"rtt min/avg/max/mdev = ([\d.]+)/([\d.]+)/([\d.]+)/([\d.]+)", ping_out)
    p_min = p_rtt.group(1) if p_rtt else "0"
    p_avg = p_rtt.group(2) if p_rtt else "0"
    p_max = p_rtt.group(3) if p_rtt else "0"
    p_jit = p_rtt.group(4) if p_rtt else "0"
    p_loss_m = re.search(r"(\d+)% packet loss", ping_out)
    p_loss   = p_loss_m.group(1) if p_loss_m else "100"
    log(f"  ping avg={p_avg}ms jitter={p_jit}ms loss={p_loss}%")

    # ── iperf helper ─────────────────────────────────────────────────────────
    # FIX #2: each UE gets its own dedicated server port (5201 + N)
    iperf_port = IPERF_BASE_PORT + N

    def iperf_run(bw, direction="dl"):
        # DL = data flows server→UE  → use -R (reverse) so client receives
        # UL = data flows UE→server  → normal direction (no flag)
        flag = "-R" if direction == "dl" else ""
        r = run(
            f"sudo ip netns exec {netns} iperf3 "
            f"-c {CORE_IP} -p {iperf_port} -t 8 -b {bw} {flag} --json",
            capture_output=True, text=True)
        out = r.stdout + r.stderr
        with open(f"{OUT_DIR}/ue{N}_iperf_{direction}_{bw}.json", "w") as jf:
            jf.write(out)
        try:
            decoder  = json.JSONDecoder()
            last_d   = None
            idx      = 0
            while idx < len(out):
                try:
                    obj, end_idx = decoder.raw_decode(out, idx)
                    if isinstance(obj, dict) and "end" in obj:
                        last_d = obj
                    idx = end_idx
                except json.JSONDecodeError:
                    idx += 1
            if last_d is None or last_d.get("error"):
                return 0.0, 100
            end = last_d["end"]
            key  = "sum_received" if direction == "dl" else "sum_sent"
            mbps = round(end[key]["bits_per_second"] / 1e6, 4)
            return mbps, 0
        except Exception:
            return 0.0, 100

    dl1,  dl1l  = iperf_run("1M",  "dl"); time.sleep(2)
    dl5,  dl5l  = iperf_run("5M",  "dl"); time.sleep(2)
    dl10, dl10l = iperf_run("10M", "dl"); time.sleep(2)
    ul1,  ul1l  = iperf_run("1M",  "ul"); time.sleep(2)
    log(f"  DL1M={dl1} DL5M={dl5} DL10M={dl10} UL1M={ul1} Mbps")

    # ── Drop detection ────────────────────────────────────────────────────────
    drop        = 0
    drop_reason = ""
    try:
        txt2 = open(stdout_log).read()
        if re.search(
            r"Disconnected|RLF|ZMQ.*timeout|radio link failure|PRACH.*fail",
            txt2, re.I):
            drop = 1
            m2 = re.search(
                r".*(Disconnected|RLF|ZMQ.*timeout|radio link failure|PRACH.*fail).*",
                txt2, re.I)
            if m2:
                drop_reason = m2.group(0)[:100].replace(",", ";")
    except Exception:
        pass

    with open(CSV_PATH, "a") as f:
        f.write(
            f"{VER},{N},{n_active},{attach_ms},OK,,{ue_ip},"
            f"{p_avg},{p_min},{p_max},{p_jit},{p_loss},"
            f"{dl1},{dl1l},{dl5},{dl5l},{dl10},{dl10l},"
            f"{ul1},{ul1l},"
            f"{drop},{drop_reason}\n")

log(f"=== {VER} 50-UE RAMP COMPLETE: {n_active}/{N_UE} attached ===")
# Signal gNB side
open(SENTINEL, "w").write(f"n_attached={n_active}")
